-- Initial migration. Mirrors packages/db/src/schema.ts and PLAN.md §3.
-- Generated by hand for Phase 1; future schema changes go through `drizzle-kit generate`.

create extension if not exists "pgcrypto";

create table if not exists "users" (
  "id" uuid primary key default gen_random_uuid(),
  "email" text not null unique,
  "monthly_budget_usd" numeric(10,4) not null default 10,
  "created_at" timestamptz not null default now()
);

create table if not exists "projects" (
  "id" uuid primary key default gen_random_uuid(),
  "user_id" uuid not null references "users"("id") on delete cascade,
  "title" text not null,
  "preset" text not null,
  "width" integer not null,
  "height" integer not null,
  "fps" integer not null default 30,
  "duration_sec" numeric(12,3) not null default 0,
  "storage_uri" text not null,
  "budget_usd" numeric(10,4) not null default 1,
  "status" text not null default 'draft',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);
create index if not exists "idx_projects_user" on "projects"("user_id");

create table if not exists "sources" (
  "id" uuid primary key default gen_random_uuid(),
  "project_id" uuid not null references "projects"("id") on delete cascade,
  "kind" text not null,
  "storage_uri" text not null,
  "duration_sec" numeric(12,3),
  "width" integer,
  "height" integer,
  "transcript" jsonb,
  "analysis" jsonb,
  "sha256" text,
  "created_at" timestamptz not null default now()
);
create index if not exists "idx_sources_project" on "sources"("project_id");

create table if not exists "jobs" (
  "id" uuid primary key default gen_random_uuid(),
  "project_id" uuid not null references "projects"("id") on delete cascade,
  "kind" text not null,
  "status" text not null,
  "worker_id" text,
  "input" jsonb,
  "output" jsonb,
  "error" text,
  "cost_usd" numeric(10,4) not null default 0,
  "gates" jsonb,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "created_at" timestamptz not null default now()
);
create index if not exists "idx_jobs_project" on "jobs"("project_id");
create index if not exists "idx_jobs_status" on "jobs"("status");

create table if not exists "agent_messages" (
  "id" uuid primary key default gen_random_uuid(),
  "project_id" uuid not null references "projects"("id") on delete cascade,
  "role" text not null,
  "content" jsonb not null,
  "tokens_in" integer,
  "tokens_out" integer,
  "cost_usd" numeric(10,4) not null default 0,
  "created_at" timestamptz not null default now()
);
create index if not exists "idx_agent_messages_project" on "agent_messages"("project_id");

create table if not exists "cost_events" (
  "id" uuid primary key default gen_random_uuid(),
  "user_id" uuid not null references "users"("id") on delete cascade,
  "project_id" uuid,
  "job_id" uuid,
  "provider" text not null,
  "unit" text not null,
  "qty" numeric(14,4) not null,
  "cost_usd" numeric(10,4) not null,
  "created_at" timestamptz not null default now()
);
create index if not exists "idx_cost_events_user" on "cost_events"("user_id");
create index if not exists "idx_cost_events_project" on "cost_events"("project_id");

create table if not exists "cached_assets" (
  "sha256" text primary key,
  "storage_uri" text not null,
  "content_type" text not null,
  "byte_size" integer not null,
  "source_url" text,
  "attribution" jsonb,
  "first_seen_at" timestamptz not null default now()
);
